[package]
name = "merlin"
# Before incrementing:
# - update CHANGELOG
# - update html_root_url
# - update README if required by semver
version = "3.0.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"
rust-version = "1.85"
readme = "README.md"
license = "MIT"
repository = "https://github.com/zkcrypto/merlin"
homepage = "https://docs.rs/merlin"
documentation = "https://docs.rs/merlin"
categories = ["cryptography"]
keywords = ["cryptography", "zero-knowledge", "fiat-shamir", "transcript"]
description = "Composable proof transcripts for public-coin arguments of knowledge"
exclude = [".travis.yml", ".gitignore"]

[dependencies]
keccak = { version = "0.2", default-features = false }
byteorder = { version = "1", default-features = false }
zeroize = { version = "1", default-features = false, features = ["zeroize_derive"] }
rand_core = { version = "0.10", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"], optional = true }

[dev-dependencies]
strobe-rs = "0.13"
curve25519-dalek = { version = "5", features = ["rand_core"] }
getrandom = { version = "0.4", features = ["sys_rng"] }
rand_chacha = "0.10"

[features]
default = ["std"]
debug-transcript = ["hex"]
std = ["byteorder/std"]
